#+Title: About Me
#+Author: Ewan Townshend
#+Options: toc:3 num:nil

* Education
*** Bachelor of Arts (Hon.) in Anthropology and Philosophy
I began post-secondary studies in 2012 at the [[https://en.wikipedia.org/wiki/University_of_Lethbridge][University of Lethbridge]]. There I was able to take a wide variety of courses before declaring a major. I cut a swathe through the humanities, social sciences, psychology and ecology, before settling on a double major in anthropology and philosophy. My research interests surrounded human cognition, and I completed a pair of capstone projects. The anthropological capstone, "Doing with Sound", supervised by [[https://directory.uleth.ca/users/james.mackenzie][Jamie MacKenzie]], deployed the semiotic taxonomy of philosopher [[https://plato.stanford.edu/entries/peirce/][C.S. Peirce]] in analyzing linguistic practices of some Amazonian societies, esp. in contexts of hunting and ritual -- an approach championed by [[https://www.mcgill.ca/anthropology/people/eduardokohn][Eduardo Kohn]]. The philosophical capstone, "Sellars on the Nature of Mental Events", supervised by [[https://directory.uleth.ca/users/brown][Bryson Brown]], elaborated on [[https://plato.stanford.edu/entries/sellars/][Wilfrid Sellars]]' approach to [[https://plato.stanford.edu/entries/intentionality/][intentionality]] ("aboutness"), with the aim of clarifying some misunderstandings in the [[https://www.ditext.com/sellars/sccor-f.html][Sellars-Chisholm Correspondence]].

*** Master of Arts (Ths.) in Philosophy
In 2018 I enrolled in graduate studies at the [[https://en.wikipedia.org/wiki/University_of_British_Columbia][University of British Columbia]] (UBC). There, my interests in mathematical and philosophical logic flourished, and my approach to cognition became more formal. Under the supervision of [[https://orisimchen.net/][Ori Simchen]], I undertook research with intent to reconcile Wilfrid Sellars' approach to meaning and representation with influential arguments from [[https://en.wikipedia.org/wiki/Hilary_Putnam][Hilary Putnam]]. After tracing the arc of Putnam's views on representation, I concluded that Sellars had diverged from a tradition in philosophical logic which supports [[https://plato.stanford.edu/entries/realism-sem-challenge/model-theory-completeness.html][model-theoretic challenges]] to Realism, too far "upstream" from Putnam for me to put them in fruitful conversation. So, in [[https://open.library.ubc.ca/media/stream/pdf/24/1.0395793/4][my M.A. thesis]] I instead attempted to elaborate on the point of divergence -- Sellars' take on [[https://en.wikipedia.org/wiki/Predication_(philosophy)][predication]] -- tracing its historical roots in Wittgenstein's [[https://en.wikipedia.org/wiki/Tractatus_Logico-Philosophicus][/Tractatus/]], and implications of differences from a traditional picture I somewhat misleadingly called the [[https://plato.stanford.edu/entries/frege/][Frege]]-[[https://plato.stanford.edu/entries/tarski/][Tarski]] model.

*** Bachelor of Computer Science
Toward the end of my master's program, we collectively responded to [[https://en.wikipedia.org/wiki/COVID-19][COVID-19]]. In the wake of that, I forwent a Ph.D. in philosophy in favor of turning my programming hobby into a career. As noted above, my interests in mathematical logic had developed, and I found myself increasingly interested in the theory of computation. The decisive factor was a recommendation for UBC's unique [[https://www.cs.ubc.ca/students/undergrad/degree-programs/bcs-program-second-degree][BCS Program]], which offers holders of a prior degree a streamlined path to an undergraduate degree in computer science without skimping on content. I enrolled in this program in 2021, and with a one-year internship in the middle, followed by a year of working while studying, finished the program in the summer of 2024.

* Interests
*** Philosophy
The opening of Sellars' [[https://www.stephanieruphy.com/wp-content/uploads/2018/09/SellarsPhilSciImage.pdf][/Philosophy and the Scientific Image of Man/]] reads:
#+begin_quote
The aim of philosophy, abstractly formulated, is to understand how things
in the broadest possible sense of the term hang together in the broadest
possible sense of the term.
#+end_quote
I understand philosophy and this aim reciprocally: philosophy is the pursuit of such understanding. But it is then difficult say, succinctly, what interests me about philosophy. Maybe it's the way that "no intellectual holds are barred". Or maybe it's just that deploying everything I know of the world, in an effort to make sense of some little part of it, pleasantly tickles my brain. In any case, this "catch all" interest allows me to learn in fields as far away from my "core" interests (cognition and computation), as physics, archaeology, or cell biology, without feeling out of place.

*** Non-classical logics
The history of so-called [[https://en.wikipedia.org/wiki/Non-classical_logic]["non-classical" logics]] is usually traced to [[https://en.wikipedia.org/wiki/C._I._Lewis][C.I. Lewis]]'s formalization of "strict" implication in response to the use of "material" implication in [[https://en.wikipedia.org/wiki/Principia_Mathematica][/Principia Mathematica/]]. History aside, I share Lewis's commitment to a [[https://www.informationphilosopher.com/knowledge/philosophers/lewis/Pragmatic_a_priori.html][pragmatic conception of /a priori/ knowledge]], esp. of "laws of logic":
#+begin_quote
The /a priori/ represents an attitude in some sense freely taken, a stipulation of the mind itself, and a stipulation which might be made in some other way if it suited our bent or need.
#+end_quote
So, I am interested in non-classical logics, as legitimately alternative systems of principles with respect to which my thinking and speaking may be governed, if being so governed -- with respect to some domain -- would be useful. In this regard, I have some stock in [[https://en.wikipedia.org/wiki/Non-monotonic_logic][non-monotonic]] and [[https://en.wikipedia.org/wiki/Paraconsistent_logic][paraconsistent]] logics, for the purposes of practical reasoning, and in [[https://en.wikipedia.org/wiki/Intuitionistic_logic][intuitionistic]] and [[https://en.wikipedia.org/wiki/Linear_logic][linear]] logics, for the purposes of thinking about computational processes.

*** Programming language theory
There is a straightforward connection between the interest in mathematical logic and an interest in programming language theory, namely the [[https://en.wikipedia.org/wiki/Curry%E2%80%93Howard_correspondence][Curry-Howard Isomorphism]]. I think [[https://en.wikipedia.org/wiki/Continuation][continuations]], specifically, are among the most fascinating beasts in the computational zoo, and the correspondence between first-class continuation handling and a double-negation embedding of classical logic in intuitionistic logic was a wild discovery (see [[https://www.cl.cam.ac.uk/~tgg22/publications/popl90.pdf][this]]). Another particularly interesting sort of beast is the /reflective tower of interpreters/ -- sure to make any programmer go "whoa". These are neatly illustrated by Nada Amin in this [[https://www.youtube.com/watch?v=SrKj4hYic5A][talk]], and their collapse covered in this [[https://www.cs.purdue.edu/homes/rompf/papers/amin-popl18.pdf][paper]]. I hope to one day fully wrap my head around them.

*** (Mostly "Good ol' fashioned") A.I.
I am interested in A.I. for various reasons, but mostly in combinatorial search problems, due in part to the sheer fun of solving them, and in part to arcane philsophical reflections ([[https://link.springer.com/article/10.1007/bf00353791][/Tractarian/]] themes in Sellars). Much of the GOFAI program was "problem solving as search", and though it has fallen out of favor, I'm holding out hope for a resurgence. However I am cognisant of issues with regarding this as a path to better understanding ourselves, /cf./ Hubert Dreyfus' famous [[https://archive.org/details/whatcomputerscan00hube][critiques]] of the GOFAI program. 

* Recreation
*** Snowboarding

I'm a long-time fan of "board sports". I grew up skateboarding, was vice president of the ULSU Board, Ski and Surf Club in my early twenties, and continue to snowboard regularly today. I cut my teeth in the Alberta Rockies, mostly on the lesser-known but very steep [[https://www.skicastle.ca/][Castle Mountain]], and occasionally on the better-known [[https://www.skilouise.com][Lake Louise.]] Since moving to Vancouver, I've held a yearly pass at [[https://www.whistlerblackcomb.com/][Whistler-Blackcomb]] and try to make it out at least once a week when the lifts are running.

*** Boxing

I spend most evenings training at a local non-profit [[https://www.eastsideboxingclub.com/][boxing gym]] serving Vancouver's Downtown Eastside. What I enjoy most about boxing is the (somewhat ironically) cerebral nature of the sport. Despite the reputation, it is a game of strategy in many ways like chess, as witnessed in the combined sport [[https://en.wikipedia.org/wiki/Chess_boxing][chess boxing]]. Nonetheless, it is a risky game, and while I don't mind some tag sparring, I don't fight competitively -- I like my brain too much.
